### ISSUE TITLE
Exception crash when connection to WHIP fails

### ISSUE THREAD

**Issue by kf6kjg** [kf6kjg/Anaximander2#14]
Exception: System.Net.Sockets.SocketException (0x80004005): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 192.168.1.137:32700
   at System.Net.Sockets.Socket.Connect(IPAddress[] addresses, Int32 port)
   at System.Net.Sockets.Socket.Connect(String host, Int32 port)
   at InWorldz.Whip.Client.RemoteServer.Connect()
   at InWorldz.Whip.Client.RemoteServer.Start()
   at AssetReader.AssetServerWHIP.Initialize(IConfig settings) in C:\projects\anaximander2\Source\AssetReader\AssetServerWHIP.cs:line 65
   at AssetReader.AssetReader..ctor(IConfigSource configSource) in C:\projects\anaximander2\Source\AssetReader\AssetReader.cs:line 84
   at Anaximander.Application.Main(String[] args)

**Comment by kf6kjg** [comment]
Fixed in commit 548aebde9df60a9f7d5cfaef7543f410e2ae855f
